## Numpy (Numerical Python)

- **It is a Python library used for working with arrays. An array is like a list, but it can store large amounts of data much more effectively.**
- **Python list can be slow and can take up more memory when working with large data, but Numpy helps solve this by: storing data effectively, performing calculations faster, and offering built-in functions for common mathematical and statistical operations**
- **Arrays are important in data science because they allow you to store data in two-dimensional or multi-dimensional forms, similar to rows and columns in a spreadsheet**
- **NumPy arrays can be used to perform operations on the entire array at once instead of looping through elements one by one**

In [9]:
pip install numpy

In [23]:
import numpy as np

even_numbers = [i for i in range(2, 50) if i % 2 == 0]
odd_numbers = [i for i in range(2, 50) if i % 2 != 0]

numbers = even_numbers + odd_numbers

print(numbers)

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49]


In [24]:
# Traditional method of multiplying lists
number_cont = []
for i in range(len(even_numbers)):
    number_cont.append(even_numbers[i] * odd_numbers[i])
print(number_cont)                      

[6, 20, 42, 72, 110, 156, 210, 272, 342, 420, 506, 600, 702, 812, 930, 1056, 1190, 1332, 1482, 1640, 1806, 1980, 2162, 2352]


In [25]:
# List comprehension method
r = [x * y for x,y in zip(even_numbers, odd_numbers)]

print(r)

[6, 20, 42, 72, 110, 156, 210, 272, 342, 420, 506, 600, 702, 812, 930, 1056, 1190, 1332, 1482, 1640, 1806, 1980, 2162, 2352]


### Creating an Array

In [37]:
even_numbers = [i for i in range(2, 50) if i % 2 == 0]
odd_numbers = [i for i in range(2, 50) if i % 2 != 0]

b = np.array(even_numbers)
d = np.array(odd_numbers)
print(b)
print(d)

[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]
[ 3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47 49]


### Arrays Operations

In [46]:
sum_bd = b + d
multiply_bd = b * d
divide_bd = d/b
minus_bd = b - d

print(sum_bd)
print(multiply_bd)

print(minus_bd)

np.around(divide_bd, decimals =2)
# print(divide_bd)

[ 5  9 13 17 21 25 29 33 37 41 45 49 53 57 61 65 69 73 77 81 85 89 93 97]
[   6   20   42   72  110  156  210  272  342  420  506  600  702  812
  930 1056 1190 1332 1482 1640 1806 1980 2162 2352]
[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]


array([1.5 , 1.25, 1.17, 1.12, 1.1 , 1.08, 1.07, 1.06, 1.06, 1.05, 1.05,
       1.04, 1.04, 1.04, 1.03, 1.03, 1.03, 1.03, 1.03, 1.02, 1.02, 1.02,
       1.02, 1.02])

In [50]:
np.sum([odd_numbers])

624

In [53]:
np.sum([even_numbers])

600

In [56]:
np.mean([even_numbers])

25.0

In [60]:
### How to summarize in two(2) decimal place

np.around(divide_bd, decimals =2)

array([1.5 , 1.25, 1.17, 1.12, 1.1 , 1.08, 1.07, 1.06, 1.06, 1.05, 1.05,
       1.04, 1.04, 1.04, 1.03, 1.03, 1.03, 1.03, 1.03, 1.02, 1.02, 1.02,
       1.02, 1.02])

### Array Dimension

Axes: Direction along which the data are arranged

- 1D Array: has 1 axis
- 2D Array: has 2 axes: rows and columns.
- 3D Array: has 3 axes: layers, rows, and columns.

In [71]:
even_numbers = [i for i in range(2, 50) if i % 2 == 0]
odd_numbers = [i for i in range(2, 50) if i % 2 != 0]

n = np.array([[even_numbers], [odd_numbers]])

print(n)
print(n.shape)
print(n.ndim)
print(n.size)

[[[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
   48]]

 [[ 3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
   49]]]
(2, 1, 24)
3
48


### List of Data Types in Numpy

- S - String
- i - integer
- b - boolean
- f - float
- c - complex float
- m - timedata
- M - Datetime
- O - object
- u - unassigned integer
- U - unicode string
- V - fixed chunk of memory for another type void
  Size can be defined for i, u, f, s, and U

#### Conversion of Data Types

In [81]:
## Conversion of data types using "astype"
b = np.array([1,2,3,4], dtype="S")
d = b.astype(float)
print(b)
print(d)

[b'1' b'2' b'3' b'4']
[1. 2. 3. 4.]


#### Some of the most important Numpy method

**1. Creating Arrays**
- np.arrays(): To create a Numpy array from a Python list or tuple
- np.zeros(), np.ones(), np.full(): To create an array with zeros, ones, or a specfic value
- np.arrange(), np.linspace(): To create an array of evenly spaced values.

In [92]:
np.array([[3,0.7, 8, 44, 8, 7.3],[8, 45, 0.0, 3, 5.5, 80]])

array([[ 3. ,  0.7,  8. , 44. ,  8. ,  7.3],
       [ 8. , 45. ,  0. ,  3. ,  5.5, 80. ]])

In [95]:
np.zeros((3, 10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [98]:
np.ones(((2, 5, 6)))

array([[[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]]])

In [101]:
np.full((2, 7), 6)

array([[6, 6, 6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6, 6, 6]])

In [105]:
np.full((2, 3, 3), 6)

array([[[6, 6, 6],
        [6, 6, 6],
        [6, 6, 6]],

       [[6, 6, 6],
        [6, 6, 6],
        [6, 6, 6]]])

In [108]:
np.arange(25) 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [111]:
np.arange(0, 20, 2) #[start, stop, step]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [114]:
np.linspace(2, 10) 

array([ 2.        ,  2.16326531,  2.32653061,  2.48979592,  2.65306122,
        2.81632653,  2.97959184,  3.14285714,  3.30612245,  3.46938776,
        3.63265306,  3.79591837,  3.95918367,  4.12244898,  4.28571429,
        4.44897959,  4.6122449 ,  4.7755102 ,  4.93877551,  5.10204082,
        5.26530612,  5.42857143,  5.59183673,  5.75510204,  5.91836735,
        6.08163265,  6.24489796,  6.40816327,  6.57142857,  6.73469388,
        6.89795918,  7.06122449,  7.2244898 ,  7.3877551 ,  7.55102041,
        7.71428571,  7.87755102,  8.04081633,  8.20408163,  8.36734694,
        8.53061224,  8.69387755,  8.85714286,  9.02040816,  9.18367347,
        9.34693878,  9.51020408,  9.67346939,  9.83673469, 10.        ])

In [117]:
np.linspace(2, 10, 10) #[start, stop, num_points]

array([ 2.        ,  2.88888889,  3.77777778,  4.66666667,  5.55555556,
        6.44444444,  7.33333333,  8.22222222,  9.11111111, 10.        ])

**2. Reshaping and Manipulating Arrays**
- np.reshape(): reshapes an array without changing its data.
- np.ravel(), np.flatten(): converts multi-dim. arrays into 1D arrays. ravel() returns a view and flatten() returns a copy.
- np.transpose(): reverses or permutes the axes of an array, often used with matrices

In [125]:
even_numbers = [i for i in range(2, 50) if i % 2 == 0]
print(even_numbers)

even_numbers_array = np.array(even_numbers)
even_numbers_array.reshape(2, 12) #rows and columns

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48]


array([[ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24],
       [26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48]])

In [128]:
b.reshape(2, 2) #rows and columns

array([[b'1', b'2'],
       [b'3', b'4']], dtype='|S1')

In [137]:
np.arange(1, 25, 3)

array([ 1,  4,  7, 10, 13, 16, 19, 22])

In [135]:
np.arange(1, 25, 3).reshape(2, 4)

array([[ 1,  4,  7, 10],
       [13, 16, 19, 22]])

In [140]:
#.ravel() and .flatten() are used to convert multi-dimensional arrays into a 1-dimensional array. 

import numpy as np

even_numbers = [i for i in range(2, 50) if i % 2 == 0]

even_numbers_array = np.array(even_numbers)

# even_numbers_array.ravel()
even_numbers_array.flatten()

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48])

In [143]:
arr = np.array([[1, 2], [3, 4]])
flat_arr = arr.flatten()

print(flat_arr)  # Output: [1 2 3 4]

flat_arr[0] = 99  # Modifying the flattened array
print(flat_arr) 
print(arr)        # Original array is unchanged: [[1 2], [3 4]]

[1 2 3 4]
[99  2  3  4]
[[1 2]
 [3 4]]


In [146]:
arr = np.array([[1, 2], [3, 4]])
ravel_arr = arr.ravel()

print(ravel_arr)  # Output: [1 2 3 4]

ravel_arr[0] = 99  # Modifying the raveled array
print(ravel_arr) 
print(arr)         # Original array is affected: [[99 2], [3 4]]

[1 2 3 4]
[99  2  3  4]
[[99  2]
 [ 3  4]]


In [149]:
t = np.array([[1, 2, 3, 4, 5, 6], [7, 8, 9, 10, 11, 12]])
print(t)

t.transpose()

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


array([[ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11],
       [ 6, 12]])

**3. Basic Math and Statistical Operations**
- np.sum(), np.mean(), and np.median(): compute the sum, mean, median of an array.
- np.max, np.min, np.argmax(), argmin(): finds the maximum and minimum values of their indices in an array.
- np.cumsum, np.cumprod(): returns the cumulative sum and product along an array.

In [154]:
arr_ten = np.arange(0, 100).reshape(10, 10)
print(arr_ten)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [157]:
np.sum(arr_ten)

4950

In [160]:
np.mean(arr_ten)

49.5

In [163]:
np.median(arr_ten)

49.5

In [166]:
np.std(arr_ten)

28.86607004772212

In [169]:
np.max(arr_ten)

99

In [172]:
np.min(arr_ten)

0

In [175]:
b = np.arange(0, 50, 2)

d = np.arange(1, 50, 2)

print(b)
print(d)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48]
[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49]


In [178]:
v = b + d

print(v)

[ 1  5  9 13 17 21 25 29 33 37 41 45 49 53 57 61 65 69 73 77 81 85 89 93
 97]


In [181]:
# Add a number to every element- Vectorization
b+ 10

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50, 52, 54, 56, 58])

In [184]:
# basic operation with indexing
b[5] + arr_ten[1,0] 

20

In [187]:
# argmin() returns the index of the smallest (minimum) value in the array.
np.argmin(arr_ten)

0

In [190]:
# argmax() returns the index of the largest (maximum) value in the array.
np.argmax(arr_ten)

99

In [193]:
# cumsum(): Computes the cumulative sum of the elements along a specified axis.
np.cumsum(b)

array([  0,   2,   6,  12,  20,  30,  42,  56,  72,  90, 110, 132, 156,
       182, 210, 240, 272, 306, 342, 380, 420, 462, 506, 552, 600])

In [196]:
# cumprod(): Computes the cumulative product of the elements along a specified axis
np.cumprod(b)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0])

**4. Sorting and Logical Operations**
- np.sort()
- np.where(): returns the indices of the elements that satify a condition.
- np.any(), np.all(): test whether any or all elements of an arrays evaluate to True

In [201]:
g = np.array([[3,0.7, 8, 44, 8, 7.3],[8, 45, 0.0, 3, 5.5, 80]])
np.sort(g)

array([[ 0.7,  3. ,  7.3,  8. ,  8. , 44. ],
       [ 0. ,  3. ,  5.5,  8. , 45. , 80. ]])

In [204]:
#The result explains the indices of where 8 appears. The first result talks about the rows at which 8 appears 
# while the second array talks about the columns at which 8 appears
# The breakdown:
# g[0, 2] = 8
# g[0, 4] = 8
# g[1, 0] = 8

np.where(g ==8)

(array([0, 0, 1], dtype=int64), array([2, 4, 0], dtype=int64))

In [207]:
np.where(g > 3)

(array([0, 0, 0, 0, 1, 1, 1, 1], dtype=int64),
 array([2, 3, 4, 5, 0, 1, 4, 5], dtype=int64))

In [215]:
[b[b>2], d[d>21]]

[array([ 4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36,
        38, 40, 42, 44, 46, 48]),
 array([23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49])]

In [213]:
# The intersect1d is used to check for what is common 

np.intersect1d(d,v)

array([ 1,  5,  9, 13, 17, 21, 25, 29, 33, 37, 41, 45, 49])

In [218]:
# Checks for any

np.any(g > 0)

True

In [221]:
# Checks for all
np.all(g>=0)

True

**5. Removing elements from an array**
- np.delete()

In [226]:
b

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48])

In [228]:
# This removes number 4 becuse ut has an index of 2
np.delete(b, 2)

array([ 0,  2,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48])

In [231]:
# Removing from a 1D array
# This removes 4 and 14 because 4 has an index of 2 while 14 has an index of 7
np.delete(b, [2, 7])

array([ 0,  2,  6,  8, 10, 12, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36,
       38, 40, 42, 44, 46, 48])

In [234]:
# This deletes the elements at the indices 2, 3, 4, 5, 6, 7, 8, and 9 from the array b.
np.delete(b, np.arange(2, 10))

array([ 0,  2, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48])

In [237]:
t

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [239]:
# To remove rows and columns from a 2D array
#So it removed the row 1
np.delete(t, 1, axis=0)  #axis=0 is for rows

array([[1, 2, 3, 4, 5, 6]])

In [242]:
# So it removed the column 1
np.delete(t, 1, axis=1) #axis=1 if for columns

array([[ 1,  3,  4,  5,  6],
       [ 7,  9, 10, 11, 12]])

In [245]:
n

array([[[ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
         34, 36, 38, 40, 42, 44, 46, 48]],

       [[ 3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
         35, 37, 39, 41, 43, 45, 47, 49]]])

In [247]:
# To remove rows and columns from a 3D array
# np.delete(array, indices, axis)
np.delete(n, 0, axis=0) #axis=0 for layer, axis=1 for row, axis=2 for column

array([[[ 3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
         35, 37, 39, 41, 43, 45, 47, 49]]])

In [250]:
z = np.array([[[0, 1, 2],
                 [3, 4, 5]],
                
                [[6, 7, 8],
                 [9, 10, 11]],
                
                [[12, 13, 14],
                 [15, 16, 17]]])
print(z)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]]


In [253]:
# To remove rows and columns from a 3D array
# np.delete(array, indices, axis)
np.delete(z, 1, axis=2) #axis=0 for layer, axis=1 for row, axis=2 for column

array([[[ 0,  2],
        [ 3,  5]],

       [[ 6,  8],
        [ 9, 11]],

       [[12, 14],
        [15, 17]]])

**6. Joining and appending array**
- np.concatenate(): is used to join to or more arrays along with the existing axis, doesnt add a new dimensions - j
extends the array along with the specified axis.
- np.stack(): is used to join arrays along with a new axis. This is different from concatenation because its creates 
a new dimension in the resulting array
- np.append()

In [258]:
b

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48])

In [260]:
np.append(b, 7)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48,  7])

In [263]:
np.concatenate((b,d), axis=0)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48,  1,  3,  5,  7,  9, 11, 13, 15, 17,
       19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49])

In [266]:
e = np.concatenate((b,d), axis=0)

print(e)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48  1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45
 47 49]


In [269]:
np.sort(e)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [272]:
arr_ten

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [275]:
q = np.arange(1, 21).reshape(10, 2)
print(q)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]
 [17 18]
 [19 20]]


In [278]:
# To concatenate row-wise, i have to reshape with 2 rows and 10 columns so it matches(reshape(2, 10))
# To concatenate column-wise, i have to reshape with 10 columns and 2 rows (reshape(10, 2))

np.concatenate((arr_ten,q), axis=1)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9,  1,  2],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19,  3,  4],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29,  5,  6],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39,  7,  8],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49,  9, 10],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 11, 12],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 13, 14],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 15, 16],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 17, 18],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 19, 20]])

In [281]:
# v.stack() combines arrays vertically (along axis 0)- first axis rows. Works like concatenate but axis =0
np.vstack((b,d))

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30,
        32, 34, 36, 38, 40, 42, 44, 46, 48],
       [ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31,
        33, 35, 37, 39, 41, 43, 45, 47, 49]])

In [287]:
# h.stack() combines arrays horizontally (along axis 1)- second axis columns. Works like concatenate but axis =1
np.hstack((b,d))

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48,  1,  3,  5,  7,  9, 11, 13, 15, 17,
       19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49])

In [290]:
np.stack((b,d))

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30,
        32, 34, 36, 38, 40, 42, 44, 46, 48],
       [ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31,
        33, 35, 37, 39, 41, 43, 45, 47, 49]])

**7. Splitting array(s)**
- np.split(): splits an array into multiple sub-array equally along a specified axis
- np.array_split() is more flexible version of np.split() because it allows unequal splits

In [297]:
# This split the array into 5 parts
np.split(b, 5)

[array([0, 2, 4, 6, 8]),
 array([10, 12, 14, 16, 18]),
 array([20, 22, 24, 26, 28]),
 array([30, 32, 34, 36, 38]),
 array([40, 42, 44, 46, 48])]

In [300]:
#For 2D array - splits into 2 parts along axis=1 columns, axis=0 rows
np.split(t, 2, axis=1)

[array([[1, 2, 3],
        [7, 8, 9]]),
 array([[ 4,  5,  6],
        [10, 11, 12]])]

In [303]:
np.hsplit(t, 2)

[array([[1, 2, 3],
        [7, 8, 9]]),
 array([[ 4,  5,  6],
        [10, 11, 12]])]

In [307]:
np.split(t, 2, axis=0)

[array([[1, 2, 3, 4, 5, 6]]), array([[ 7,  8,  9, 10, 11, 12]])]

In [310]:
np.vsplit(t, 2)

[array([[1, 2, 3, 4, 5, 6]]), array([[ 7,  8,  9, 10, 11, 12]])]

In [313]:
np.array_split(t, 5, axis=0)

[array([[1, 2, 3, 4, 5, 6]]),
 array([[ 7,  8,  9, 10, 11, 12]]),
 array([], shape=(0, 6), dtype=int32),
 array([], shape=(0, 6), dtype=int32),
 array([], shape=(0, 6), dtype=int32)]

In [316]:
#For 3D arrays (or higher), you can split them depth-wise, which splits along the third axis
np.dsplit(z, 3)

[array([[[ 0],
         [ 3]],
 
        [[ 6],
         [ 9]],
 
        [[12],
         [15]]]),
 array([[[ 1],
         [ 4]],
 
        [[ 7],
         [10]],
 
        [[13],
         [16]]]),
 array([[[ 2],
         [ 5]],
 
        [[ 8],
         [11]],
 
        [[14],
         [17]]])]

**8. Random Number Generator**
- np.random.rand() and np.random.randint(): generates random numbers(floats and integers)

In [321]:
np.random.rand(4)  #generates 4 random floats numbers

array([0.65858775, 0.01119964, 0.72336103, 0.52630536])

In [324]:
np.random.rand(4).round(2)

array([0.14, 0.38, 0.33, 0.29])

In [327]:
np.round(np.random.rand(4), decimals =2)

array([0.8 , 0.57, 0.84, 0.1 ])

In [330]:
np.random.randint(50, 100, 10) #starts from 50, ends at 100, 10 numbers

array([92, 78, 53, 99, 63, 67, 73, 85, 72, 79])